version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: algo
    environment:
      POSTGRES_DB: algo-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: