services:
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'user']
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_DB=algo
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    ports:
      - '5434:5432'
    volumes:
      - ./backend/src/db/migrations:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local